-- Magnitude Analysis
---- Find the total number of customers by country
SELECT 
country, 
COUNT(customer_id) AS total_customers 
FROM gold.dim_customers 
GROUP BY country 
ORDER BY total_customers DESC

---- Find total customers by gender
SELECT 
gender, 
COUNT(customer_id) AS total_customers 
FROM gold.dim_customers 
GROUP BY gender 
ORDER BY total_customers DESC

---- Find total products by category
SELECT 
category,
COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT 
category,
AVG(product_cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
